version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: always
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - /docker/local-certs:/certs
    command: --ssl --sslcert /certs/portainer-selfsigned.crt --sslkey /certs/portainer-selfsigned.key

volumes:
  portainer_data:
